### ISSUE TITLE
03_math1.pdf wrong statement

### ISSUE THREAD

**Issue by ali-tunahan** [inzva/Algorithm-Program#68]
In page 11 under Multiplication it is written that "if a = c, then a mod n · b mod n ≡  c mod n". However this should be "if a * b = c, then a mod n · b mod n ≡  c mod n".

Source: https://brilliant.org/wiki/modular-arithmetic/#modular-arithmetic-multiplication

**Comment by kayacanv** [comment]
Hi @ali-tunahan ,
You are right, it should be changed.
The bundles are currently not used by inzva, and are not maintained. If you like to open pr and fix it,  I'd be happy to review and confirm.

To anyone who wants to make a contributions, here are the steps:
1. Find the corresponding .tex file you wish to update and open in a text editor.
2. Make the desired changes to the file.
3. Use a TeX compiler(we are using LaTeX) to render the updated .tex file into a new PDF.
4. Open a pull request on Github to make the changes. 

Thanks
